version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
    image: reactimage
    ports:
      - "3000:3000"
    # environment:
    #   - API_URL=http://django:8000
    #   - API_URL_BROWSER=http://localhost:8000
    
# networks:
#   default:
#     external:
#       name: climatetrade_local
